### ISSUE TITLE
Crash on TFTP 'put'

### ISSUE THREAD

**Issue by icb-** [psychomario/PyPXE#105]
Trying to `put` a file crashes the TFTP thread. Further TFTP `get`s don't work until restarting `PyPXE`, but the other parts continue to function.

    2015-06-05 00:45:25,250 [DEBUG] PyPXE.TFTP.Client.('127.0.0.1', 28227) Recieving request...
    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/usr/local/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "pypxe/tftp.py", line 275, in listen
        rlist, _, _ = select.select([self.sock] + [client.sock for client in self.ongoing if not client.dead], [], [], 0)
    AttributeError: Client instance has no attribute 'sock'

I don't have time to fix this right now, so if someone else can take a look, that would be great. Personally, I would like to fix this by supporting `put` operations, but that might be out of scope for `PyPXE`.

**Comment by psychomario** [comment]
I can probably take a look at this today.

`put` is definitely out of scope for `PyPXE` as PXE roms have no need to upload files. This requirement should be handled by a full TFTP implementation.

**Comment by psychomario** [comment]
I've written up a PR to fix this in #106 

Would it be worth adding an option to relaunch services on crash? We'd still have the log but it would save having to restart the whole server. It shouldn't be too tricky to impement.

**Comment by mmattioli** [comment]
@psychomario perhaps it's best to leave it crashed because then it mandates user intervention because if it's crashing them something obviously is wrong in the first place
