### ISSUE TITLE
Drop Privileges

### ISSUE THREAD

**Issue by icb-** [psychomario/PyPXE#108]
We need to start as `root` since we're opening sockets below port 1024, but we should drop privileges after.

**Comment by psychomario** [comment]
This will be the job of `*.__init__` as that is where the binding is done.

Is `nobody` available/suitable on all *nix?

**Comment by icb-** [comment]
I think a configurable user, with defaulting to not dropping privileges is reasonable. `nobody` probably works universally, but I don't know of any spec requiring it.

**Comment by psychomario** [comment]
I'm working on this now.

Do we want to drop group as well?

**Comment by icb-** [comment]
Probably should drop group too.

**Comment by psychomario** [comment]
I should have a PR ready shortly

**Comment by mmattioli** [comment]
Do we have any sort of confirmation that using `nobody` requires no configuration of users/groups? There shouldn't be a need to create/edit users/groups regardless of the advantage to doing so...

**Comment by psychomario** [comment]
[this](http://refspecs.linux-foundation.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/usernames.html) implies `nobody` should exist, but we can't know for every platform.

**Comment by mmattioli** [comment]
@psychomario @icb- what are the advantages to this exactly? Are we attempting to mitigate a security threat we aren't yet aware of or is there a specific threat we've found somewhere that this patches? None of our operations perform writes on the host machine, only reads, so is there something we're afraid that we're leaving ourselves open to?

**Comment by psychomario** [comment]
This just protects us from issues in the stack above us I think (kernel, python interpreter). IIRC it also allows users to kill the process if it's as their username.

**Comment by mmattioli** [comment]
Killing it shouldn't be an issue, the convenience of not having to be root or use sudo is definitely outweighed by the complexity of implementing this along with the uncertainty of whether or not we've implemented it well enough for it to be cross-platform. Have we come across any issues in the stack (kernel, Python interpreter, etc.)?

**Comment by psychomario** [comment]
Fair enough. And no, not personally. They have existed in the past, but it's *unlikely* it'll affect us.

**Comment by mmattioli** [comment]
I think we should close this as well as #109, if we come across a serious issue or find a way to cleanly and confidently implement this cross-platform we can re-visit this. Fair enough?

**Comment by psychomario** [comment]
Sounds good.
