### ISSUE TITLE
DHCP for non-PXEClients?

### ISSUE THREAD

**Issue by bryfry** [psychomario/PyPXE#117]
Is there a reason that [validate_req](https://github.com/psychomario/PyPXE/blob/c52d87686a62c8ae0488074d470d87e8e2f0914b/pypxe/dhcp.py#L284) doesn't have a case where `if not self.mode_proxy` it would return True in order to service dhcp requests post-pxe?

**Comment by mmattioli** [comment]
It was briefly discussed, and [agreed upon](https://github.com/psychomario/PyPXE/issues/62#issuecomment-93550720), in #62 that PyPXE's goal is very simple: serve PXE requests and _only_ serve PXE requests. The DHCP server exists because it's a part of PXE, not because it's meant to stand alone.

In other words, we're not trying to re-invent the wheel here :wink:; we're just trying to implement that bare minimum to reliably service PXE clients.

**Comment by bryfry** [comment]
Apologies I definitely skimmed over this line from the documentation.md

> By default only requests declaring the 'PXEClient' value dhcp option 60 are served, this is defined by PXE specifications If you're using PyPXE as a library you can change this behavior extending the DHCP class and overwriting the validateReq method.

I do have a question on your comment from the previous thread on this topic:

> the purpose of the built-in DHCP server isn't to be a standalone DHCP server; it's purpose is to send PXE information to clients via DHCP with the option of providing IP/NM/GW if needed

Am I missing a different type of deployment?  How would you use PyPXE's DHCP server in complement with another DHCP server? I was under the impression that if you wanted PXE functionality in a network with an existing DHCP server you would use the proxyDHCP functionality.  If I'm using the normal DHCP portion of this code I think it would be reasonable to expect it to also service the basic IP assignment of the the post-pxe os.  This is why I suggested to validate a request that is not mode_proxy.

Thanks for your thoughts!

**Comment by mmattioli** [comment]
The idea is to use the DHCP server to PXE boot and that's it. A typical use case would be if someone ran PyPXE from their laptop to massively clone machines with no established network; thereafter, a network would be established which would serve DHCP leases to the newly imaged machines.

**Comment by bryfry** [comment]
Thanks, that is understandable.
