### ISSUE TITLE
Logger.getChild() incompatible with Python 2.6

### ISSUE THREAD

**Issue by icb-** [psychomario/PyPXE#136]
[Logger.getChild()](https://docs.python.org/2/library/logging.html#logging.Logger.getChild) doesn't exist until Python 2.7. PyPXE is supposed to support Python 2.6, which is the latest normally available on CentOS 6. Can we see about implementing a workaround so we can still support older versions of Python?

**Comment by psychomario** [comment]
So we use `.getChild()` in 4 places at the moment. Three are at the root level (`PyPXE.[thing]`) and one [is at the level below](https://github.com/psychomario/PyPXE/blob/11176d2875b3665dca7f4f481ef70ec1752ab17d/pypxe/tftp.py#L27). I propose we create our own `getChild` implementation similar to the following:

```
def getChild(logger, name):
    return logging.getLogger("{0}.{1}".format(logger.name, name))
```

A full example follows:

```
import logging

def getChild(logger, name):
    return logging.getLogger("{0}.{1}".format(logger.name, name))

sys_logger = logging.getLogger('PyPXE')
handler = logging.StreamHandler()
formatter = logging.Formatter('%(asctime)s [%(levelname)s] %(name)s %(message)s')
handler.setFormatter(formatter)
sys_logger.addHandler(handler)
sys_logger.setLevel(logging.INFO)

sys_logger.info("foo")
getChild(sys_logger, "bar").info("baz")
```

```
bash-3.2$ python2.6 test.py
2016-06-03 09:09:19,411 [INFO] PyPXE foo
2016-06-03 09:09:19,411 [INFO] PyPXE.bar baz
```

It would be easy to subclass the Logger object, but may add uneccessary complexity.

Opinions?

**Comment by icb-** [comment]
That looks reasonable to me, and works as expected in Python 2.6. Thanks!

**Comment by psychomario** [comment]
If you've got this working locally would you be able to submit a PR? I can't get to my dev box for a while at the moment.

**Comment by icb-** [comment]
Sure. I should be able to get to it this weekend.
