### ISSUE TITLE
Publising PyPXE to pip

### ISSUE THREAD

**Issue by urosjarc** [psychomario/PyPXE#139]
I wanted to use PyPXE in my project but I was kinda suprised that I did not found this lib in PIP index.
Is this lib some other usage method that I was not aware?

**Comment by psychomario** [comment]
There's no particular reason this project is not on PIP as far as I know. I'm not 100% sure how pip works but you should just be able to clone the repo and `pip install .` to achieve the same results.

**Comment by urosjarc** [comment]
Well I can make some pull request to add some makefile which I usa3ally use 1955524051 9i9n 4my projects if this is all right4 for you?

**Comment by psychomario** [comment]
We already have a `setup.py` for building and installing. What do you wish to add?

**Comment by urosjarc** [comment]
Something like this [makefile](https://github.com/urosjarc/mylinux/blob/develop/makefile#L79)

**Comment by psychomario** [comment]
I don't think we particularly need that, as the `setup.py` script can be used manually. @mmattioli comments?

**Comment by urosjarc** [comment]
Well to bo honest, I will integrate this lib in to my project and pxe will be the main service, so I want to become contributor for making more extensive docs for this project since I want to fully understand pxe specs. and this project.

**Comment by mmattioli** [comment]
@urosjarc I'm not entirely sure how adding a makefile or making any of the changes you're proposing help you with what you're looking to achieve; can you elaborate on why the `setup.py` file does not work for you?

**Comment by urosjarc** [comment]
Hm, I made a confusion with my thoughts. Lets forget about makefile and focus to solve this issue. Can you guys upload this lib to pip index.
```
python setup.py sdist
python setup.py bdist_whee
twine upload dist/*
```

**Comment by psychomario** [comment]
https://pypi.python.org/pypi/PyPXE
