### ISSUE TITLE
Be able to set blksize through config

### ISSUE THREAD

**Issue by Apachez-** [psychomario/PyPXE#150]
Today the blksize (for tftpd) in PyPXE is hardcoded to 512 (bytes).

It would be great if the blksize could be specified through cli and/or through json-config file.

Except for being able to handle larger files when altering the blksize (on the other hand tftp.py already supports rolling block counter) fully utilizing the available MTU will make the filetransfer faster.

Note:

If I quickly alter "self.blksize = 512" into what should be a usable maxsize of a mtu 1500 network that is "self.blksize = 1468" the transfer works but it will timeout for the last block so it seems that something else other than "self.blksize" must be changed at the same time if the blksize is modified to be higher than 512 bytes.

The crash looks like this:

"
2017-03-11 04:33:53,195 [DEBUG] PyPXE.TFTP.Client.('192.168.0.1', 37041) Sending block 48
2017-03-11 04:33:53,195 [INFO] PyPXE.TFTP.Client.('192.168.0.1', 37041) Completed sending /tftpboot/file.bin
2017-03-11 04:33:58,196 [DEBUG] PyPXE.TFTP.Client.('192.168.0.1', 37041) Recieving request...
2017-03-11 04:33:58,196 [WARNING] PyPXE.TFTP.Client.('192.168.0.1', 37041) Ignoring out of sequence ACK received for block 1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/pypxe/tftp.py", line 272, in listen
    rlist, _, _ = select.select([self.sock] + [client.sock for client in self.ongoing if not client.dead], [], [], 1)
AttributeError: Client instance has no attribute 'sock'
"

Compared to when using blksize = 512:

"
2017-03-11 04:38:42,252 [DEBUG] PyPXE.TFTP.Client.('192.168.0.1', 49037) Sending block 137
2017-03-11 04:38:42,252 [INFO] PyPXE.TFTP.Client.('192.168.0.1', 49037) Completed sending /tftpboot/file.bin
"

Also note that when PyPXE crashes (due to changed self.blksize value) the file being transfered have a different checksum so obviously something went very wrong here.

Client is "tftp" installed on Ubuntu 16.10.

Testcode is (put below into test_tftp.sh (dont forget to change ip of the tftp server to connect to) and chmod +x test_tftp.sh and finally run it with ./test_tftp.sh):

#!/bin/bash

tftp 192.168.0.1 <<'EOF'
binary
get file.bin
quit
EOF

**Comment by icb-** [comment]
Per RFC1350:

> [The] file is sent in fixed length blocks of 512 bytes.

RFC2347 extends this to allow negotiating a higher blocksize. `PyPXE` supports this negotiation.

Many TFTP clients do this properly, like [FreeBSD's tftp](https://www.freebsd.org/cgi/man.cgi?query=tftp) and iPXE.

Changing the blksize default away from 512 violates the RFCs, but will probably work with many clients. Given that the last message before the stacktrace in your crash, is about receiving an out-of-order ack, it doesn't look like your client is able to deal with non-standard block sizes. A packet capture and the output of running `PyPXE` in debug mode would help pinpoint the problem.

**Comment by psychomario** [comment]
Given @icb-'s comments above, I don't think this will be implemented, as we want to stick to the RFC.

**Comment by Apachez-** [comment]
Has this negotition been verified?

Comparing PyPXE with tftpgui 2.2 (since both are opensource and both are written in python) the tftpgui will send the packets at 1460 byte size to the client but the very same client fetching a file through tftp from PyPXE will only have the file sent with 512 byte packets.

**Comment by psychomario** [comment]
I've just used the busybox tftp client, which lets you specify the blocksize with `-b`, and I've confirmed with wireshark that the blksize is used as instructed. Both for lower (128) and higher (1300) byte blksizes.

**Comment by icb-** [comment]
Try a packet capture ([Wireshark](https://www.wireshark.org/)) and make sure your client is attempting to negotiate a different `blksize`. Adding some logging to [`tftp.parse_options()`](https://github.com/psychomario/PyPXE/blob/master/pypxe/tftp.py#L97) and [`tftp.reply_options()`](https://github.com/psychomario/PyPXE/blob/master/pypxe/tftp.py#L117) might help too.
