### ISSUE TITLE
Support Static Assignments, Per-host Options

### ISSUE THREAD

**Issue by icb-** [psychomario/PyPXE#27]
It would be nice to support static assignment, and sending specific options (and values) to each host. For example, only responding to one specific host is desirable, rather than any PXE DHCP request received.

**Comment by kwbales** [comment]
Is anybody currently looking into this? If not, I may hack around on this over the next couple of weeks as part of some Zero Touch Provisioning work I am doing for network devices.

**Comment by psychomario** [comment]
Not that I'm aware of. I would welcome your contributions!

I would note that I don't know how safe this code is for production use, it doesn't follow all the RFCs to the letter.

**Comment by psychomario** [comment]
@kwbales Did you ever manage to get anywhere with this? If not I have the time to look into it.

**Comment by psychomario** [comment]
@mmattioli Why did you reopen this? Have I missed something?

**Comment by mmattioli** [comment]
@psychomario technically we shouldn't close this until it's merged with `master` :wink:

**Comment by psychomario** [comment]
@mmattioli Fair enough, sounds good to me.
