### ISSUE TITLE
tlvparse() Doesn't Account for Vendor-specific Options

### ISSUE THREAD

**Issue by psychomario** [psychomario/PyPXE#33]
Vendor specific options can be nested.

See line 208 of dhcpd.py for an example.

**Comment by mmattioli** [comment]
@psychomario I'm going to remove this from the v1.1 milestone as after #59 is merged we should have more than enough for a v1.1 release.

**Comment by psychomario** [comment]
Seems sensible. I'm not sure this is specifically needed anymore, as we're not aiming for a complete implementation.

On a related note, I think the amount of features that are going into this merge warrants more than a minor version bump, perhaps 2.0 is in order?

**Comment by mmattioli** [comment]
Perhaps. Once #59 is merged let's re-evaluate how much has changed and whether it warrants a v1.5 or the jump to v2.0

**Comment by mmattioli** [comment]
@psychomario when you get a chance, can you review this and see if we should even keep it open? Just going through old issues and checking to see if any of them are even relevant given the recent/upcoming changes.

**Comment by psychomario** [comment]
@mmattioli Given that we aren't aiming to be a full DHCP implementation, and the vendor specific options that we need are being parsed properly, I think this has become a non-issue. At least for the forseeable future.
