### ISSUE TITLE
Support TFTP Retransmit, Timeout

### ISSUE THREAD

**Issue by icb-** [psychomario/PyPXE#39]
The TFTP module doesn't support timeouts, or retransmitting dropped blocks. The block number is blindly incremented at the end of every block sent, and the trigger to send the next one is receiving an ACK for any block.

**Comment by mmattioli** [comment]
@psychomario 8cd1e7580e706a0ecf73c3c943306c8749cd6b48 seems to be your most recent commit to the development branch in regards to this issue. Looks like you've done some testing but just wanted to check with you if that has actually been done. My plan was to open a PR and do some tidying up with everything (whitespace, comments, PEP8, etc.) and then test everything before merging to master but if there was no testing done yet I won't bother.

**Comment by psychomario** [comment]
This was done at the same time as #40, so the same testing applies.
