### ISSUE TITLE
Support UEFI

### ISSUE THREAD

**Issue by psychomario** [psychomario/PyPXE#46]
Proposal
---
Currently our included pxelinux files only support BIOS, which is now old and superseded by UEFI. We would need to include pxelinux files relevant to UEFI, more generally the *.e32 and *.e64 files.

Required files listed [here](http://www.syslinux.org/wiki/index.php/Library_modules)

Reasoning
---
Almost all new hardware is shipped with UEFI loaders. Without this feature we limit who can use the software to only those booting via BIOS.

**Comment by psychomario** [comment]
This is sort of implemented, I'm going to close this until specific testing gets done and specific issues come up.

**Comment by mmattioli** [comment]
I just got around to reviewing the code for this and it looks fine albeit some minor comment cleanliness and string formatting but we can leave those for now and clean them all up when we're done reviewing the rest of the code.
