### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by psychomario** [psychomario/PyPXE#68]
Is a test suite something we want?

[`unittest`](https://docs.python.org/2/library/unittest.html) is part of python so we could use that. I've personally never done testing but I'm more than happy to investigate and implement it.

Some of the parts, namely the networking, will be more tricky to create tests for, but I'd imagine we can mock up a socket.socket class to verify what we're sending back.

Furthermore, if we have testing we can use something like [Travis](https://travis-ci.org/) for automated testing.

**Comment by mmattioli** [comment]
Travis is so clunky and isn't always accurate. I'm not opposed to using `unittest` but at the same time I feel like this project isn't _that_ big that whatever testing needs to be done can't be done by hand.

**Comment by psychomario** [comment]
As with testing, I've never used Travis before.

A lot of testing can be done by hand, but some of the combinations are quite involved to test, and at least some automated testing would be beneficial.

I'll look into it when we have merged #59 and #65.
