### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by psychomario** [psychomario/PyPXE#73]
We currently don't support windows, but on the whole there is no reason we can't.

I've got a Windows 8.1 x64 VM running Python 2.7.9 I'm used for testing. I will update this issue with things I come across

### Issues:

 * `os.getuid()` not available on Windows. `AttributeError`. There does not seem to be the concept of privileged ports in windows so this warning doesn't apply anyway. Given that we want each module to be able to be independant, we should probably remove the `getuid` call, and add a `try...except socket.error` on the calls to `bind` in each module. This would also let us catch other errors more helpfully, such as `Address already in use`

* `os.chroot` calls fail, as discussed in #72, again `AttributeError`. We ought to `try...except` on chroot and log it, again, discussed #72.

* Also related to #72, TFTP paths come in as absolute paths (`/pxelinux.0`). Without chroot this is an error. Same for HTTP.

* __BUG__ TFTP file reading is failing. `os.path.getsize` reports the correct filesize, `.read()`ing the file does not give the correct size. Solution: (Applies elsewhere) __All files should be opened `b` (binary mode)__ (xref #59)
    * tftp `read` `self.ongoing[address]['handle']...`
    * httpd `handleRequest` `handle = open...`

### Untested:
 * DHCP Server mode

**Comment by mmattioli** [comment]
See [my comment](https://github.com/psychomario/PyPXE/pull/72#issuecomment-94598196) from #72 in regards to this; I feel it's a bad idea and it'd be more beneficial to focus our efforts in other areas.

**Comment by psychomario** [comment]
The relevant bugs are in the bug list, so I'll close this as not worth the effort.

**Comment by gh0st** [comment]
So is windows supported now?

**Comment by icb-** [comment]
Short answer is "I don't know." I don't have any Windows systems to test on. I would happily accept a PR for Windows support, but I have no way to verify any future changes wouldn't break it.

**Comment by gh0st** [comment]
Ah. What I meant by that is I've created windows images and I want to install windows onto systems via pypxe. I've got pypxe to show them in the boot menu but when I select a windows image from a machine from the boot menu it sits at
```
Loading memdisk... ok
Loading win7pe.iso...
```
Then the machine eventually boots into the OS that's already on the disk, instead of to the `.iso`.

This is what my boot menu looks like.
```
LABEL Windows7
    MENU LABEL Windows7
    KERNEL memdisk 
    APPEND iso initrd=win7pe.iso

LABEL Windows10
    MENU LABEL Windows10
    KERNEL memdisk 
    APPEND iso initrd=win10pe.iso
```

This is what PyPXE shows on terminal.
```
2019-07-16 01:44:08,180 [WARNING] PyPXE.TFTP.Client.('192.168.1.44', 49168) Request too big, attempting transfer anyway.
```

Eventually on the client it errors out with a message as such
```
...
Ramdisk at 0xcc8cb000, length 0x90cb6000
command line: BOOT_IMAGE=memdisk iso ignited=win7pe.iso
MEMDISK: Image seems to have fractional end cylinder
MEMDISK: Image appears to be truncated
Disk is hd96, 40118 K, C/H/S = 65535/255/15 (El Torito/El Torito),
Using safe INT 15h access to high memory
Code 1860, memento 468, codlin 41, stack 512
Total size needed = 2881 bytes, allocating 3K
Old dos memory at 0x83c00 (map says 0x9d8000), loading at 0x83000
1588: 0xffff   15E801: 0x3c00 0x1f00
INT 13 08: Success, count = 1, BPT = 0000:0000
Drive probing gives drive shift limit 0xe1
old: int13 = f000756c  int15 = e8000324  int1e  = f000efc7
new: int13 = 8300000a int15 = 830003fd int1e = f000efc7
Loading boot sector... booting...
CDBOOT: Cannot boot from CD - Code: 5
```

The `win7pe.iso` is 157MB and the `win10pe.iso` is 290MB. I've been told to try `KERNEL raw` but PyPXE errors out when I do that.

Thoughts?

**Comment by icb-** [comment]
The "Request too big, attempting transfer anyway." warning means that the file you're trying to transfer over tftp is larger than 65536 blocks (about 33.5MB with the default 512 byte block size). It tries to transfer it anyway, hoping that the client supports it (this is technically a violation of the spec, there's no provision for block roll-over in any published TFTP spec, but it works with most clients.) I think it probably did transfer ok, but there's another problem later with the Windows image (or compatibility with the computer it's being run on.) I would try booting into iPXE and use [wimboot](http://ipxe.org/wimboot), but I've never installed Windows with PXE, so I don't have any first-hand experience.

**Comment by gh0st** [comment]
@icb- so, in `PyPXE/netboot` there's a file called `boot.http.ipxe`. If I run PyPXE with `python -m pypxe.server --dhcp-proxy --dhcp-server-ip 192.168.1.106 --dhcp-fileserver 192.168.1.106 --tftp --tftp-server 192.168.1.106 --verbose tftp,http --ipxe --http` I can `CTRL+B` on the test machine and get to the iPXE prompt...but where would I go from there? On the pypxe server the logs then read
```
2019-11-05 04:43:19,734 [INFO] PyPXE Starting TFTP server...
2019-11-05 04:43:19,737 [INFO] PyPXE Starting DHCP server in ProxyDHCP mode...
2019-11-05 04:43:19,741 [INFO] PyPXE Starting HTTP server...
2019-11-05 04:43:19,743 [INFO] PyPXE PyPXE successfully initialized and running!
2019-11-05 04:43:49,831 [INFO] PyPXE.TFTP.Client.('192.168.1.17', 2071) Completed sending /home/pi/PyPXE/netboot/chainload.kpxe
```
This is after I've booted another machine on the same network from NIC. I then hit `CTRL+B` to get the iPXE prompt but I'm unsure of what to do from here. Also, following [these instructions](http://ipxe.org/wimboot#create_the_ipxe_script) should I be entering `http://192.168.1.106/boot.ipxe` at `iPXE>`?

**Comment by icb-** [comment]
The HTTP 404 is being sent because `/home/pi/PyPXE/netboot/wimboot` isn't a file.

`2019-11-14 00:39:34,050 [WARNING] PyPXE.HTTP Sending 404 Not Found to 192.168.1.17:28440 for /home/pi/PyPXE/netboot/wimboot`
