### ISSUE TITLE
Improve CLI Argument Groups

### ISSUE THREAD

**Issue by mmattioli** [psychomario/PyPXE#80]
Proposal
===
As `--help` is getting quite long now, we could use `parser.add_argument_group()` to split up related sections (e.g `--dhcp-*`, `--netboot-*`).

**Comment by mmattioli** [comment]
@psychomario can you include the fix for this in #70 so that we fix two issues in one PR?

**Comment by psychomario** [comment]
@mmattioli Sounds good, I'll get on this too after the merge.
