### ISSUE TITLE
Remove Short CLI Options from --help

### ISSUE THREAD

**Issue by psychomario** [psychomario/PyPXE#85]
Only the options for DHCP are available as short options, and half of those aren't very intuitive.

Should we remove all short options and be consistent with long options?

Now we have the JSON config file it's not really required to save on typing as options can be set there.

**Comment by mmattioli** [comment]
Probably isn't a bad idea considering `--help` is getting somewhat long now even with argument groupings. If you want to make a branch and submit a PR before I do the cleanup that'd be awesome

**Comment by psychomario** [comment]
@mmattioli I've done so in #86

**Comment by mmattioli** [comment]
Just merged, thanks! :+1:

**Comment by psychomario** [comment]
There's a lot of stuff I've missed out of the `README.md` over the last few PRs. Do you want me to create a new PR with all that I've missed, or do you want to catch it during the cleanup PR?

**Comment by mmattioli** [comment]
I'll catch it in the cleanup PR. If you want, write it all down somewhere and when I open the PR you can make a comment and just copy/paste it all.
