### ISSUE TITLE
TFTP Sequence Wraps Not Working

### ISSUE THREAD

**Issue by icb-** [psychomario/PyPXE#94]
TFTP sequence wraps aren't working. After we hit block 65535, we wrap around to sequence number 0 again, and start logging "Ignoring duplicated ACK received for block 65535" until the client gives up. See https://www.cloudshark.org/captures/07ebe14c792b for a packet capture. I've trimmed the packets between 414 and 415.

Fixing this may be as simple as taking the sequence numbers modulo 65536 when checking if we have a duplicate (or out of sequence) ack.

**Comment by psychomario** [comment]
The proposed fix seems sensible, the relevant sections being in `Client.handle()`

**Comment by mmattioli** [comment]
@icb- if you want to make a branch based off of `development` and submit a PR to `development` once you have a fix that'd be awesome. Thanks!
